# library(ReportMaster)
# Sys.setenv(R_CONFIG_ACTIVE = "default")
# library(shiny)
# library(bslib)

# Set environment and initialize parameters


#' Get a Preview of the Report
#' @description This function invokes the Shiny app to preview the report
#'  generated by the ReportMaster package.
#' @param snr The school number.
#' @param audience The audience for the report.
#' @param ubb Whether the school is a UBB school.
#' @param ganztag Whether the school is a Ganztagsschule.
#' @param stype The school type.
#' @examples
#' \dontrun{
#' ReportPreview(snr = "8934", audience = "sus", ubb = FALSE, ganztag = FALSE, stype = "gm")
#' }
#' @return Shiny app
#' @export


ReportPreview <- function(snr, audience, ubb, ganztag, stype) {
  # Get initial parameters and data
  snrparams <- get_parameter(
    snr = snr,
    audience = audience,
    ubb = ubb,
    ganztag = ganztag,
    stype = stype
  )

  tmp.data <- snrparams$data
  tmp.meta <- snrparams$meta
  tmp.n <- snrparams$n
  tmp.rprtpckg <- snrparams$rprtpckg
  tmp.survey <- snrparams$survey
  tmp.report <- snrparams$report
  tmp.dauer <- snrparams$dauer
  tmp.freitext <- snrparams$freitext
  tmp.name <- snrparams$name


  # Check if report already exists
  initial_report_path <- base::file.path("res", base::paste0(snr, "_2024"),
                                         base::paste0(snr, "_results_", audience, ".pdf"))
  initial_report_exists <- base::file.exists(initial_report_path)

  md_path <- system.file(
    "app/app_txt.md",  # Path relative to inst/
    package = "ReportMaster" # Your package name
  )


  # If file doesn't exist, create a temporary file with fallback content
  if (md_path == "") {
    warning("Could not find content.md in package, using fallback content")

    fallback_content <- "# Could not find content.md in package"

    md_path <- tempfile(fileext = ".md")
    writeLines(fallback_content, md_path)
  }

  ui <- bslib::page_sidebar(
    title = "OES Report View",

    sidebar = bslib::sidebar(
      width = "33%",

      # School information at the top of sidebar
      bslib::card(
        class = "mb-3",
        bslib::card_header(
          "Schule:",
          class = "bg-light"
        ),
        bslib::card_body(
          shiny::h2(tmp.name),
          shiny::tags$br(),
          shiny::h3(class = "text-muted", paste("Befragung:", audience)),
          shiny::tags$br(),
          shiny::h3(class = "text-muted", paste("N:", tmp.n[1]))
        )
      ),

      # Plot selection dropdown
      shiny::selectInput("selected_plot", "Bitte Plot auswählen:",
                         choices = tmp.meta,
                         selected = tmp.meta[1]),

      shiny::downloadButton("download", "Download Abbildung", class = "btn-standard w-100"),

      shiny::hr(),

      shiny::uiOutput("generate_report_ui"),
      shiny::uiOutput("progress_ui"),
      shiny::uiOutput("download_report_ui")
    ),

    # Main panel with tabs for plot and information
    bslib::navset_card_tab(
      full_screen = TRUE,
      bslib::nav_panel(
        "Ergebnisse",
        shiny::uiOutput("dynamic_card_header"),
        shiny::plotOutput("plot1")
      ),
      bslib::nav_panel(
        "Allgemeine Informationen",
        shiny::includeMarkdown(md_path)
      )
    )
  )

  server <- function(input, output, session) {
    # Initialize reactive values
    report_available <- shiny::reactiveVal(initial_report_exists)
    is_running <- shiny::reactiveVal(FALSE)

    # Dynamic card header for plot
    output$dynamic_card_header <- shiny::renderUI({
      shiny::req(input$selected_plot)
      plots_report <- sub(".*#(.*)", "\\1", input$selected_plot)

      if (ubb) {
        header_report <- plots_headers_ubb
        header_report <- header_report |> dplyr::filter(plot == plots_report)
      }else {
        header_report <- plots_headers
        header_report <- header_report |> dplyr::filter(plot == plots_report)
      }

      bslib::card_header(header_report$header1)
    })

    # Generate plot function
    generate_plot <- function() {
      ReportMaster::create_PlotWeb(
        meta = input$selected_plot,
        snr = snr,
        audience = audience,
        report = tmp.report,
        ubb = ubb,
        data = tmp.data
      )
    }

    # Display the plot
    output$plot1 <- shiny::renderPlot({
      shiny::req(input$selected_plot)
      generate_plot()
    })

    # Generate Report UI
    output$generate_report_ui <- shiny::renderUI({
      if (!report_available()) {
        shiny::div(
          shiny::actionButton("generate_report",
                              label = shiny::span(
                                shiny::icon("file-pdf"),
                                "Generate Report"
                              ),
                              class = "btn-primary w-100"),
          shiny::div(
            style = "margin-top: 5px; font-size: 0.8em; color: #666;",
            shiny::icon("clock"),
            "This process may take several minutes."
          )
        )
      }
    })

    # Download handler for plots
    output$download <- shiny::downloadHandler(
      filename = function() {
        base::paste0("plot-", input$selected_plot, ".png")
      },
      content = function(file) {
        base::tryCatch({
          grDevices::png(file, width = 8, height = 6, units = "in", res = 150)
          base::print(generate_plot())
          grDevices::dev.off()
        }, error = function(e) {
          if(grDevices::dev.cur() > 1) grDevices::dev.off()
          base::stop("Error generating plot: ", e$message)
        })
      },
      contentType = "image/png"
    )

    # Progress UI
    output$progress_ui <- shiny::renderUI({
      if (is_running()) {
        shiny::div(
          style = "margin-top: 15px;",
          shiny::div(class = "text-center",
                     shiny::tags$i(class = "fa fa-spinner fa-spin fa-2x"),
                     shiny::tags$p("Generating report...")
          )
        )
      }
    })

    # Download Report UI
    output$download_report_ui <- shiny::renderUI({
      if (report_available()) {
        shiny::div(
          style = "margin-top: 15px;",
          shiny::downloadButton("download_report", "PDF Report", class = "btn-success w-100")
        )
      }
    })

    # Download handler for report
    output$download_report <- shiny::downloadHandler(
      filename = function() {
        base::paste0(snr, "_results_", audience, ".pdf")
      },
      content = function(file) {
        report_path <- base::file.path("res", base::paste0(snr, "_2024"),
                                       base::paste0(snr, "_results_", audience, ".pdf"))

        if (!base::file.exists(report_path)) {
          base::stop("Report file not found at: ", report_path)
        }
        base::file.copy(report_path, file)
      },
      contentType = "application/pdf"
    )

    # Handle report generation
    shiny::observeEvent(input$generate_report, {
      is_running(TRUE)
      report_available(FALSE)

      results <- "sus"

      base::tryCatch({
        ReportMaster::run_Parallel(
          snr = snr,
          audience = audience,
          stype = stype,
          ubb = ubb,
          ganztag = ganztag,
          results = results
        )
        is_running(FALSE)
        report_available(TRUE)
        shiny::showNotification("Report generation completed!", type = "message")
      },
      error = function(e) {
        is_running(FALSE)
        report_available(FALSE)
        shiny::showNotification(
          base::paste("Error generating report:", e$message),
          type = "error"
        )
      })
    })
  }

  shiny::shinyApp(ui, server)
}

#ReportPreview(snr = "8934", audience = "sus", ubb = FALSE, ganztag = FALSE, stype = "gm")



